### ISSUE TITLE
Not working if string to search for contains Unicode characters

### ISSUE THREAD

**Issue by certainlyakey** [rajeshvaya/sublime-online-searcher#3]
Have to report another bug - if a string to be searched contains a Unicode character, search doesn't work and console gives this error:

```
Traceback (most recent call last):
  File "OnlineSearch in /Users/alex/Library/Application Support/Sublime Text 3/Installed Packages/OnlineSearch.sublime-package", line 62, in search
  File "X/webbrowser.py", line 70, in open_new_tab
  File "X/webbrowser.py", line 62, in open
  File "X/webbrowser.py", line 622, in open
UnicodeEncodeError: 'ascii' codec can't encode characters in position 47-54: ordinal not in range(128)
```

**Comment by ykqmain** [comment]
Recur on macOS
